project:
  type: website
  output-dir: docs

website:
  search: false
  title: "Marco Wang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - about.qmd

format:
  html:
    include-after-body: translate.html
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



